ERROR_SPECIFICATION_FILE = -1
ERROR_MARKET_DATA_FILE = -2
ERROR_PARAMS_FILE = -3
ERROR_NETWORK_FILE = -4
ERROR_OPERATIONAL_DATA_FILE = -5
ERROR_NETWORK_MODEL = -6
ERROR_NETWORK_OPTIMIZATION = -7

BUS_PQ = 1
BUS_PV = 2
BUS_REF = 3
BUS_ISOLATED = 4

GEN_REFERENCE = 0
GEN_CONV = 1
GEN_RES_WIND = 2
GEN_RES_SOLAR = 3
GEN_RES_OTHER = 4
GEN_RES_CONTROLLABLE = 5
GEN_INTERCONNECTION = 6
GEN_CONTROLLABLE_TYPES = [GEN_REFERENCE, GEN_CONV, GEN_RES_CONTROLLABLE]
GEN_CURTAILLABLE_TYPES = [GEN_RES_WIND, GEN_RES_SOLAR, GEN_RES_OTHER, GEN_INTERCONNECTION]
GEN_RENEWABLE_TYPES = [GEN_RES_WIND, GEN_RES_SOLAR, GEN_RES_OTHER, GEN_RES_CONTROLLABLE]

BRANCH_UNKNOWN_RATING = 999.99
TRANSFORMER_MAXIMUM_RATIO = 1.17
TRANSFORMER_MINIMUM_RATIO = 0.83

ENERGY_STORAGE_MAX_ENERGY_STORED = 0.90
ENERGY_STORAGE_MIN_ENERGY_STORED = 0.10
ENERGY_STORAGE_RELATIVE_INIT_SOC = 0.50
ENERGY_STORAGE_MAX_POWER_CHARGING = 1.00
ENERGY_STORAGE_MAX_POWER_DISCHARGING = 1.00

OBJ_MIN_COST = 1
OBJ_CONGESTION_MANAGEMENT = 2

COST_GENERATION_CURTAILMENT = 250.00
COST_CONSUMPTION_CURTAILMENT = 250.00
PENALTY_SLACK_VOLTAGE = 1e6
PENALTY_SLACK_BRANCH_FLOW = 1e6
PENALTY_GENERATION_CURTAILMENT = 1e6
PENALTY_LOAD_CURTAILMENT = 1e6
PENALTY_FLEX_LOAD_ENERGY_BALANCE_CONS = 1e6
PENALTY_ESS_SLACK_FEASIBILITY = 10e6
PENALTY_ESS_COMPLEMENTARITY = 1e6
PENALTY_ESS_CAPACITY_INSTALLED = 1e6
PENALTY_ESS_CAPACITY_AVAILABLE = 1e6
PENALTY_ESS_CAPACITY_DEGRADATION = 1e6
PENALTY_ESS_CAPACITY_RELATIVE = 1e6
PENALTY_ESS_APPARENT_POWER = 1e6
PENALTY_ESS_SOC = 1e6
PENALTY_ESS_DAY_BALANCE = 1e6
PENALTY_ESS_SLACK = 1e6
PENALTY_ESS_RESERVE = 1e6
PENALTY_ESS_EXPECTED_VALUES = 1e6
PENALTY_ESS_DEGRADATION = 1e6
PENALTY_FLEX = 1e6
PENALTY_NODE_BALANCE = 1e6
PENALTY_BRANCH_CURRENT = 1e6
PENALTY_GEN_SETPOINT = 1e6
PENALTY_INTERFACE_VOLTAGE = 1e6
PENALTY_INTERFACE_POWER_FLOW = 1e6
PENALTY_INTERFACE_ESS = 1e6

DATA_ACTIVE_POWER = 1
DATA_REACTIVE_POWER = 2
DATA_UPWARD_FLEXIBILITY = 3
DATA_DOWNWARD_FLEXIBILITY = 4
DATA_COST_FLEXIBILITY = 5

SMALL_TOLERANCE = 1e-5
ADMM_ADAPTIVE_PENALTY_FACTOR = 0.05
ADMM_CONVERGENCE_REL_TOL = 5e-2
ERROR_PRECISION = 3     # Nth decimal place
